Context:
  Timeout: "30s"

PostgresHost: "localhost"
PostgresPort: "5432"
PostgresUser: "postgres"
PostgresPassword: "1"
PostgresDatabase: "posts"

KafkaUrl: ":9092"
GRPCPort: ":7001"
HTTP_PORT: ":8080"
SMTP_SENDER: "bahodirovamubina505@gmail.com"
SMTP_PASSWORD: "qext gmhd owss kqpe"