Context:
  Timeout: "30s"

PostgresHost: "postgres-db"
PostgresPort: "5437"
PostgresUser: "postgres"
PostgresPassword: "1"
PostgresDatabase: "posts"

KafkaUrl: "kafka_posts:9092"
GRPCPort: "posts_service:7001"
HTTP_PORT: ":8080"
SMTP_SENDER: "bahodirovamubina505@gmail.com"
SMTP_PASSWORD: "qext gmhd owss kqpe"