version: '3.9'

services:
  gateway:
    container_name: gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - post_service
    networks:
      - posts

        
  postgres-db:
    container_name: posts
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
      POSTGRES_DB: posts
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - posts
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d posts" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - posts
    volumes:
      - ./api-gateway/internal/pkg/scripts/migration:/migrations
    command:
      [ "-path", "/migrations", "-database",
        "postgres://postgres:1@postgres-db:5432/posts?sslmode=disable",
        "up" ]
    depends_on:
      postgres-db:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper_posts
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - posts

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka_posts
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    networks:
      - posts
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_posts:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_posts:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  post_service:
    container_name: posts_service
    build: ./post-service
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: posts
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
      POSTGRES_DATABASE: posts
    ports:
      - "7001:7001"
    networks:
      - posts

networks:
  posts:
    driver: bridge

volumes:
  db:
