// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/pkg/scripts/submodule/logs.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level       string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *LogCreateRequest) Reset() {
	*x = LogCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCreateRequest) ProtoMessage() {}

func (x *LogCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCreateRequest.ProtoReflect.Descriptor instead.
func (*LogCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogCreateRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogCreateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogCreateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type LogCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level       string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *LogCreateResponse) Reset() {
	*x = LogCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCreateResponse) ProtoMessage() {}

func (x *LogCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCreateResponse.ProtoReflect.Descriptor instead.
func (*LogCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogCreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogCreateResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogCreateResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type LogGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level       string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CreatedAt   string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy   int64  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (x *LogGetResponse) Reset() {
	*x = LogGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGetResponse) ProtoMessage() {}

func (x *LogGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGetResponse.ProtoReflect.Descriptor instead.
func (*LogGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogGetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogGetResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogGetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogGetResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogGetResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LogGetResponse) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type LogGetAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log   []*LogGetResponse `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	Count int32             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LogGetAll) Reset() {
	*x = LogGetAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGetAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGetAll) ProtoMessage() {}

func (x *LogGetAll) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGetAll.ProtoReflect.Descriptor instead.
func (*LogGetAll) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogGetAll) GetLog() []*LogGetResponse {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *LogGetAll) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LogUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level       string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *LogUpdateRequest) Reset() {
	*x = LogUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogUpdateRequest) ProtoMessage() {}

func (x *LogUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogUpdateRequest.ProtoReflect.Descriptor instead.
func (*LogUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{4}
}

func (x *LogUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogUpdateRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogUpdateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogUpdateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type FilterLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit       int64  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset      int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Page        int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Level       string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *FilterLog) Reset() {
	*x = FilterLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLog) ProtoMessage() {}

func (x *FilterLog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLog.ProtoReflect.Descriptor instead.
func (*FilterLog) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{5}
}

func (x *FilterLog) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FilterLog) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FilterLog) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FilterLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *FilterLog) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetId) Reset() {
	*x = GetId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetId) ProtoMessage() {}

func (x *GetId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetId.ProtoReflect.Descriptor instead.
func (*GetId) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{6}
}

func (x *GetId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LogVoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogVoid) Reset() {
	*x = LogVoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogVoid) ProtoMessage() {}

func (x *LogVoid) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_scripts_submodule_logs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogVoid.ProtoReflect.Descriptor instead.
func (*LogVoid) Descriptor() ([]byte, []int) {
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP(), []int{7}
}

var File_internal_pkg_scripts_submodule_logs_proto protoreflect.FileDescriptor

var file_internal_pkg_scripts_submodule_logs_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x22, 0x65, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x76, 0x0a, 0x11, 0x4c, 0x6f,
	0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x22, 0x4b, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x12, 0x28, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x75, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x09, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x09, 0x0a, 0x07,
	0x4c, 0x6f, 0x67, 0x56, 0x6f, 0x69, 0x64, 0x32, 0x8f, 0x02, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x28,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_scripts_submodule_logs_proto_rawDescOnce sync.Once
	file_internal_pkg_scripts_submodule_logs_proto_rawDescData = file_internal_pkg_scripts_submodule_logs_proto_rawDesc
)

func file_internal_pkg_scripts_submodule_logs_proto_rawDescGZIP() []byte {
	file_internal_pkg_scripts_submodule_logs_proto_rawDescOnce.Do(func() {
		file_internal_pkg_scripts_submodule_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_scripts_submodule_logs_proto_rawDescData)
	})
	return file_internal_pkg_scripts_submodule_logs_proto_rawDescData
}

var file_internal_pkg_scripts_submodule_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_pkg_scripts_submodule_logs_proto_goTypes = []any{
	(*LogCreateRequest)(nil),  // 0: protos.LogCreateRequest
	(*LogCreateResponse)(nil), // 1: protos.LogCreateResponse
	(*LogGetResponse)(nil),    // 2: protos.LogGetResponse
	(*LogGetAll)(nil),         // 3: protos.LogGetAll
	(*LogUpdateRequest)(nil),  // 4: protos.LogUpdateRequest
	(*FilterLog)(nil),         // 5: protos.FilterLog
	(*GetId)(nil),             // 6: protos.GetId
	(*LogVoid)(nil),           // 7: protos.LogVoid
}
var file_internal_pkg_scripts_submodule_logs_proto_depIdxs = []int32{
	2, // 0: protos.LogGetAll.log:type_name -> protos.LogGetResponse
	0, // 1: protos.LogService.Create:input_type -> protos.LogCreateRequest
	6, // 2: protos.LogService.GetDetail:input_type -> protos.GetId
	4, // 3: protos.LogService.Update:input_type -> protos.LogUpdateRequest
	6, // 4: protos.LogService.Delete:input_type -> protos.GetId
	5, // 5: protos.LogService.GetList:input_type -> protos.FilterLog
	1, // 6: protos.LogService.Create:output_type -> protos.LogCreateResponse
	2, // 7: protos.LogService.GetDetail:output_type -> protos.LogGetResponse
	7, // 8: protos.LogService.Update:output_type -> protos.LogVoid
	7, // 9: protos.LogService.Delete:output_type -> protos.LogVoid
	3, // 10: protos.LogService.GetList:output_type -> protos.LogGetAll
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pkg_scripts_submodule_logs_proto_init() }
func file_internal_pkg_scripts_submodule_logs_proto_init() {
	if File_internal_pkg_scripts_submodule_logs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LogCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LogCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LogGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LogGetAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LogUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FilterLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_scripts_submodule_logs_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LogVoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_scripts_submodule_logs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_scripts_submodule_logs_proto_goTypes,
		DependencyIndexes: file_internal_pkg_scripts_submodule_logs_proto_depIdxs,
		MessageInfos:      file_internal_pkg_scripts_submodule_logs_proto_msgTypes,
	}.Build()
	File_internal_pkg_scripts_submodule_logs_proto = out.File
	file_internal_pkg_scripts_submodule_logs_proto_rawDesc = nil
	file_internal_pkg_scripts_submodule_logs_proto_goTypes = nil
	file_internal_pkg_scripts_submodule_logs_proto_depIdxs = nil
}
